### ISSUE TITLE
Revisit the `deployment` event type

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/github-actions-buildtypes#6]
I'm curious about the deployment event in GHA and how it relates to SLSA. We have it listed as a supported event in the github-actions-buildtypes repo but AFAICT it doesn't really make sense to me as an important event to support.
https://github.com/slsa-framework/github-actions-buildtypes/tree/main/workflow/v1#build-definition

We currently have it listed as a supported event type for BYOB in verify-token
https://github.com/slsa-framework/slsa-github-generator/blob/921bfa1c304f3adc597c69e6d64f3a9ca34080a0/.github/actions/verify-token/src/validate.ts#L34

AFAICT, deployments on GHA get created through the normal 'push' to branch/tag style events when you specify an 'environment' on a job. So this is presumably when you're actually building your artifact. It's also presumably where the "deployment" to the environment actually happens.
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment

The deployment event gets triggered when the deployment gets created, but [doesn't always have a GIT ref ](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment)and is perhaps for doing some kind of cleanup or maybe some validation after the deployment actually happens? I'm not sure it's really relevant to SLSA.

Is there a clear example somewhere in the GitHub docs (or elsewhere) that shows how it might be relevant for builds?

**Comment by MarkLodato** [comment]
I've never used deployments before so I just guessed looking at the documentation. I don't have an opinion here.

**Comment by ianlewis** [comment]
I vote for removing it as a supported type. We can always add it back if there is need and we better understand the use case.
